name: Build and test 99 problems with swift

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: "5.7"
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test